services:
  - type: web
    name: a9global-api
    runtime: node
    region: singapore
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: JWT_SECRET
        value: a9global_jwt_secret_2026
