services:
  - type: web
    name: a9global-api
    env: node
    region: singapore
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    rootDir: backend
    envVars:
      - key: JWT_SECRET
        value: a9global_jwt_secret_2026
