'use client';
import { useState } from 'react';
import { useI18n } from "@/lib/i18n";

const FAQS: Record<string, [string,string][]> = {
  hotels: [['What time is check-in/check-out?','Check-in is 2:00 PM and check-out is 12:00 PM. Early check-in or late check-out can be arranged.'],['Is breakfast included?','Most hotels include complimentary breakfast. Check the hotel details page for specifics.'],['Do you offer airport transfers?','Yes, we arrange airport transfers for all partner hotels. Select the option during booking.'],['Can I modify my hotel booking?','Yes, modifications can be made up to 48 hours before check-in date.'],['What is the cancellation policy?','Free cancellation up to 72 hours before check-in. Within 72 hours, first night charge applies.']],
  cars: [['What types of vehicles are available?','We offer sedans, SUVs, vans, and luxury vehicles from Toyota, Honda, Mercedes, and more.'],['Is fuel included in the rental price?','Yes, all car rentals include fuel for local trips. Long-distance trips may have additional charges.'],['Can I hire a driver?','Yes, all our vehicles come with professional drivers as standard.'],['What documents do I need?','A valid passport or national ID is required for booking.'],['Can I rent a car for multiple days?','Yes, we offer daily, weekly, and monthly rental options with discounted rates.']],
  visas: [['How long does visa processing take?','Processing time varies by country: 3-7 business days for most, 2-4 weeks for some.'],['What documents are required?','Passport (6+ months validity), passport photos, application form, and supporting documents vary by country.'],['Can you help with urgent visas?','Yes, we offer express processing for an additional fee. Contact us for details.'],['What is the visa success rate?','Our visa success rate is 95%+ for countries we process.'],['Do you handle business visas?','Yes, we process both tourist and business visas for 30+ countries.']],
  insurance: [['What does travel insurance cover?','Medical expenses, trip cancellation, lost baggage, flight delays, and emergency evacuation.'],['How much does travel insurance cost?','Plans start from Ks 50,000 per trip. Premium plans available for comprehensive coverage.'],['Can I buy insurance after booking?','Yes, insurance can be purchased anytime before your trip begins.'],['How do I file a claim?','Contact our 24/7 support hotline. We assist with the entire claims process.'],['Is insurance mandatory for all trips?','Not mandatory but highly recommended for international travel.']],
  cruises: [['What routes are available?','We offer Irrawaddy River cruises, Chindwin River expeditions, and Andaman Sea cruises.'],['How long are the cruises?','Cruises range from 1-day excursions to 14-day luxury voyages.'],['Are meals included?','Yes, all cruises include meals. Luxury cruises include premium dining.'],['What is the best time for cruising?','October to March offers the best weather for river cruises in Myanmar.'],['Do cruises have cabin categories?','Yes, most cruises offer Standard, Deluxe, and Suite cabins.']],
  tours: [['What is included in the tour package?','Hotel, transportation, guide, entrance fees, and most meals. See each tour for details.'],['Can I customize a tour?','Yes, we offer custom tour packages. Contact us with your preferences.'],['What languages do guides speak?','Our guides speak English, Chinese, Japanese, Thai, and French.'],['How large are tour groups?','Group sizes range from 2-15 people. Private tours are also available.'],['What is the best season for Myanmar tours?','November to February is ideal — cool and dry weather.']],
};

const FAQ_MM: Record<string, [string,string][]> = {
  hotels: [['Check-in နဲ့ check-out အချိန် ဘယ်လိုလဲ?','Check-in သည် နေ့လည် ၂:၀၀၊ check-out သည် ၁၂:၀၀ ဖြစ်သည်။ စောစော check-in သို့မဟုတ် နောက်ကျ check-out ကို စီစဉ်ပေးနိုင်သည်။'],['မနက်စာ ပါဝင်ပါသလား?','ဟိုတယ်အများစုတွင် အခမဲ့မနက်စာ ပါဝင်သည်။ အသေးစိတ်ကို ဟိုတယ်စာမျက်နှာတွင် ကြည့်ပါ။'],['လေဆိပ်အကြိုအပို့ ရှိပါသလား?','ဟုတ်ပါသည်၊ ပါတနာဟိုတယ်အားလုံးအတွက် လေဆိပ်အကြိုအပို့ စီစဉ်ပေးပါသည်။ ကြိုတင်မှာယူစဉ် ရွေးချယ်နိုင်ပါသည်။'],['ဟိုတယ်ကြိုတင်မှာယူမှုကို ပြင်ဆင်နိုင်ပါသလား?','ဟုတ်ပါသည်၊ check-in မတိုင်မီ နာရီ ၄၈ အတွင်း ပြင်ဆင်နိုင်ပါသည်။'],['ဖျက်သိမ်းခြင်းမူဝါဒက ဘယ်လိုလဲ?','Check-in မတိုင်မီ နာရီ ၇၂ အတွင်း အခမဲ့ ဖျက်သိမ်းနိုင်သည်။ ၇၂ နာရီအတွင်းဆိုလျှင် ပထမညကြေး ကောက်ခံပါသည်။']],
  cars: [['ဘယ်လိုကားအမျိုးအစားတွေ ရှိပါသလဲ?','Toyota, Honda, Mercedes အပါအဝင် ဆီဒင်၊ SUV၊ ဗန်နှင့် ဇိမ်ခံကားများ ရှိပါသည်။'],['ငှားရမ်းခတွင် ဆီပါဝင်ပါသလား?','ဟုတ်ပါသည်၊ ပြည်တွင်းခရီးများအတွက် ဆီအားလုံး ပါဝင်သည်။ ဝေးလံသောခရီးများတွင် အပိုကြေး ရှိနိုင်ပါသည်။'],['ယာဉ်မောင်း ငှားနိုင်ပါသလား?','ဟုတ်ပါသည်၊ ကျွန်ုပ်တို့၏ ကားအားလုံးတွင် ကျွမ်းကျင်သော ယာဉ်မောင်းများ ပါဝင်ပါသည်။'],['ဘယ်စာရွက်စာတမ်းတွေ လိုပါသလဲ?','ကြိုတင်မှာယူရန်အတွက် နိုင်ငံကူးလက်မှတ် သို့မဟုတ် နိုင်ငံသားစိစစ်ရေးကတ် လိုအပ်ပါသည်။'],['ရက်ပေါင်းများစွာ ကားငှားနိုင်ပါသလဲ?','ဟုတ်ပါသည်၊ လျှော့စျေးနှုန်းများဖြင့် နေ့စဉ်၊ အပတ်စဉ်နှင့် လစဉ် ငှားရမ်းမှုရွေးချယ်စရာများ ရှိပါသည်။']],
  visas: [['ဗီဇာ ဆောင်ရွက်ချိန် ဘယ်လောက်ကြာပါသလဲ?','ဆောင်ရွက်ချိန်သည် နိုင်ငံအလိုက် ကွဲပြားသည်- အများစုအတွက် ၃-၇ ရက်၊ အချို့အတွက် ၂-၄ ပတ် ကြာပါသည်။'],['ဘယ်စာရွက်စာတမ်းတွေ လိုပါသလဲ?','နိုင်ငံကူးလက်မှတ် (သက်တမ်း ၆ လကျော်)၊ ဓာတ်ပုံ၊ လျှောက်လွှာနှင့် နိုင်ငံအလိုက် အထောက်အကူစာရွက်များ လိုပါသည်။'],['အရေးပေါ်ဗီဇာ ကူညီပေးနိုင်ပါသလဲ?','ဟုတ်ပါသည်၊ အပိုကြေးဖြင့် အမြန်ဆောင်ရွက်ပေးမှုကို ဆောင်ရွက်ပေးပါသည်။ အသေးစိတ်အတွက် ဆက်သွယ်ပါ။'],['ဗီဇာအောင်မြင်မှုနှုန်း ဘယ်လောက်လဲ?','ကျွန်ုပ်တို့ ဆောင်ရွက်ပေးသော နိုင်ငံများအတွက် အောင်မြင်မှုနှုန်း ၉၅%+ ရှိပါသည်။'],['စီးပွားရေးဗီဇာ ဆောင်ရွက်ပေးပါသလား?','ဟုတ်ပါသည်၊ နိုင်ငံပေါင်း ၃၀+ အတွက် ခရီးသွားနှင့် စီးပွားရေးဗီဇာ နှစ်မျိုးလုံး ဆောင်ရွက်ပေးပါသည်။']],
  insurance: [['ခရီးသွားအာမခံက ဘာတွေ အကျုံးဝင်ပါသလဲ?','ဆေးကုသစရိတ်၊ ခရီးစဉ်ဖျက်သိမ်းမှု၊ ခရီးဆောင်အိတ်ပျောက်ဆုံးမှု၊ လေယာဉ်နှောင့်နှေးမှုနှင့် အရေးပေါ်ကယ်ထုတ်မှုတို့ ပါဝင်ပါသည်။'],['ခရီးသွားအာမခံ ဘယ်လောက်ကျပါသလဲ?','အစီအစဉ်များသည် တစ်ခရီးလျှင် Ks ၅၀,၀၀၀ မှ စတင်ပါသည်။ ကျယ်ကျယ်ပြန့်ပြန့် အကျုံးဝင်မှုအတွက် ပရီမီယံအစီအစဉ်များ ရှိပါသည်။'],['ကြိုတင်မှာယူပြီးမှ အာမခံဝယ်နိုင်ပါသလဲ?','ဟုတ်ပါသည်၊ ခရီးမစတင်မီ အချိန်မရွေး အာမခံဝယ်ယူနိုင်ပါသည်။'],['တောင်းခံမှု ဘယ်လိုတင်ရပါသလဲ?','ကျွန်ုပ်တို့၏ ၂၄/၇ ဖုန်းလိုင်းကို ဆက်သွယ်ပါ။ တောင်းခံမှုလုပ်ငန်းစဉ်တစ်ခုလုံးကို ကူညီဆောင်ရွက်ပေးပါသည်။'],['အာမခံသည် မဖြစ်မနေလား?','မဖြစ်မနေမဟုတ်သော်လည်း နိုင်ငံတကာခရီးအတွက် အထူးအကြံပြုပါသည်။']],
  cruises: [['ဘယ်လမ်းကြောင်းတွေ ရှိပါသလဲ?','ဧရာဝတီမြစ် သင်္ဘောစီးခရီးများ၊ ချင်းတွင်းမြစ် စူးစမ်းခရီးများနှင့် ကပ္ပလီပင်လယ် သင်္ဘောစီးခရီးများ ရှိပါသည်။'],['သင်္ဘောခရီးတွေ ဘယ်လောက်ကြာပါသလဲ?','သင်္ဘောခရီးများသည် ၁ ရက်တာ မှ ရက် ၁၄ ကြာ ဇိမ်ခံခရီးအထိ ရှိပါသည်။'],['အစားအစာတွေ ပါဝင်ပါသလဲ?','ဟုတ်ပါသည်၊ သင်္ဘောခရီးအားလုံးတွင် အစားအစာများ ပါဝင်သည်။ ဇိမ်ခံခရီးများတွင် အဆင့်မြင့်စားသောက်မှု ပါဝင်ပါသည်။'],['သင်္ဘောစီးရန် အကောင်းဆုံးအချိန်က ဘယ်အချိန်လဲ?','အောက်တိုဘာမှ မတ်လသည် မြန်မာနိုင်ငံ မြစ်ကြောင်းခရီးများအတွက် အကောင်းဆုံးရာသီဥတု ဖြစ်ပါသည်။'],['သင်္ဘောအခန်းအမျိုးအစားများ ရှိပါသလဲ?','ဟုတ်ပါသည်၊ သင်္ဘောအများစုတွင် Standard၊ Deluxe နှင့် Suite အခန်းများ ရှိပါသည်။']],
  tours: [['ခရီးစဉ်အစီအစဉ်တွင် ဘာတွေပါဝင်ပါသလဲ?','ဟိုတယ်၊ ယာဉ်၊ လမ်းညွှန်၊ ဝင်ကြေးများနှင့် အစားအစာအများစု ပါဝင်ပါသည်။ အသေးစိတ်ကို ခရီးစဉ်တစ်ခုချင်းစီတွင် ကြည့်ပါ။'],['ခရီးစဉ်ကို စိတ်ကြိုက်ပြင်ဆင်နိုင်ပါသလဲ?','ဟုတ်ပါသည်၊ စိတ်ကြိုက်ခရီးစဉ်များ ဆောင်ရွက်ပေးပါသည်။ သင့်လိုအပ်ချက်များဖြင့် ဆက်သွယ်ပါ။'],['လမ်းညွှန်များက ဘာဘာသာစကားတွေ ပြောပါသလဲ?','ကျွန်ုပ်တို့၏ လမ်းညွှန်များသည် အင်္ဂလိပ်၊ တရုတ်၊ ဂျပန်၊ ထိုင်းနှင့် ပြင်သစ် ဘာသာစကားများကို ပြောဆိုပါသည်။'],['အဖွဲ့တွေ ဘယ်လောက်ကြီးပါသလဲ?','အဖွဲ့အရွယ်အစားမှာ ၂-၁၅ ဦး ဖြစ်ပါသည်။ သီးသန့်ခရီးစဉ်များလည်း ရရှိနိုင်ပါသည်။'],['မြန်မာနိုင်ငံခရီးအတွက် အကောင်းဆုံးရာသီက ဘယ်အချိန်လဲ?','နိုဝင်ဘာမှ ဖေဖော်ဝါရီသည် အကောင်းဆုံးဖြစ်သည် — အေးပြီး ခြောက်သွေ့သော ရာသီဥတု။']],
};

export default function FAQAccordion({ section }: { section: string }) {
  const { t, lang } = useI18n();
  const [open, setOpen] = useState<number>(-1);
  const faqs = lang === "mm" ? (FAQ_MM[section] || FAQS[section] || []) : (FAQS[section] || []);
  return (
    <div style={{ maxWidth: 800, margin: '0 auto', padding: '40px 20px' }}>
      <h2 style={{ fontFamily: "'Playfair Display',serif", fontSize: 24, color: '#0A1628', textAlign: 'center', marginBottom: 24 }}>{t("common.faqTitle")}</h2>
      {faqs.map(([q, a], i) => (
        <div key={i} style={{ borderBottom: '1px solid #eee', marginBottom: 8 }}>
          <button onClick={() => setOpen(open === i ? -1 : i)} style={{ width: '100%', textAlign: 'left', padding: '14px 0', background: 'none', border: 'none', cursor: 'pointer', display: 'flex', justifyContent: 'space-between', alignItems: 'center', fontSize: 15, fontWeight: 600, color: '#0A1628' }}>
            {q}
            <span style={{ color: '#D4AF37', fontSize: 20 }}>{open === i ? '−' : '+'}</span>
          </button>
          {open === i && <p style={{ padding: '0 0 14px', color: '#555', fontSize: 14, lineHeight: 1.6 }}>{a}</p>}
        </div>
      ))}
    </div>
  );
}
