export const dynamic = 'force-dynamic';

import { NextRequest, NextResponse } from 'next/server';
import { getAll, create } from '@/lib/persistentStore';

// ═══════════════════════════════════════════════════════════════════════
//  Seed Data — 12 items per section
// ═══════════════════════════════════════════════════════════════════════

const SEED = {
  tours: [
    { title: "Yangon City Highlights", slug: "yangon-city-highlights", destination: "Yangon", description: "Discover the colonial charm and golden pagodas of Myanmar's largest city. Visit Shwedagon, stroll through downtown streets, and explore Bogyoke Market.", priceMMK: 250000, priceUSD: 119, duration: 3, durationUnit: "Days", groupSize: 12, rating: 4.5, reviewCount: 128, images: ["/images_v2/tour-yangon-v2.jpg", "/images_v2/unsplash-6-v2.jpg"], amenities: ["AC Transport", "English Guide", "Breakfast", "Water"], included: ["Hotel pickup/drop", "Meals", "Guide", "Transport"], excluded: ["Flights", "Visa fees", "Personal expenses"], featured: true, status: "active" },
    { title: "Bagan Temple Explorer", slug: "bagan-temple-explorer", destination: "Bagan", description: "Explore over 2,000 ancient temples scattered across the mystical plains of Bagan. Sunrise balloon rides and sunset pagoda views await.", priceMMK: 450000, priceUSD: 215, duration: 5, durationUnit: "Days", groupSize: 15, rating: 4.8, reviewCount: 256, images: ["/images_v2/tour-bagan-v2.jpg", "/images_v2/unsplash-7-v2.jpg"], amenities: ["AC Transport", "English Guide", "Breakfast", "Lunch"], included: ["Hotel", "Meals", "Guide", "Transport", "Sunset views"], excluded: ["Flights", "Visa fees", "Balloon ride"], featured: true, status: "active" },
    { title: "Mandalay Royal Heritage", slug: "mandalay-royal-heritage", destination: "Mandalay", description: "Visit the last royal capital of Myanmar. Explore Mandalay Palace, U Bein Bridge, and the ancient cities of Amarapura, Sagaing, and Mingun.", priceMMK: 320000, priceUSD: 152, duration: 4, durationUnit: "Days", groupSize: 15, rating: 4.6, reviewCount: 189, images: ["/images_v2/tour-mandalay-v2.jpg", "/images_v2/unsplash-8-v2.jpg"], amenities: ["AC Transport", "English Guide", "Breakfast", "Boat Ride"], included: ["Hotel", "Meals", "Guide", "Boat tour"], excluded: ["Flights", "Visa fees", "Gratuities"], featured: false, status: "active" },
    { title: "Inle Lake Discovery", slug: "inle-lake-discovery", destination: "Inle Lake", description: "Glide across the tranquil waters of Inle Lake. Witness floating gardens, leg-rowing fishermen, and vibrant five-day markets.", priceMMK: 380000, priceUSD: 181, duration: 4, durationUnit: "Days", groupSize: 10, rating: 4.7, reviewCount: 167, images: ["/images_v2/tour-inle-v2.jpg", "/images_v2/unsplash-9-v2.jpg"], amenities: ["Boat", "English Guide", "Breakfast", "Lunch"], included: ["Hotel", "Meals", "Boat tours", "Market visits"], excluded: ["Flights", "Visa fees", "Souvenirs"], featured: true, status: "active" },
    { title: "Ngapali Beach Retreat", slug: "ngapali-beach-retreat", destination: "Ngapali", description: "Unwind on pristine white-sand beaches with crystal-clear waters. Snorkeling, seafood feasts, and breathtaking sunsets included.", priceMMK: 550000, priceUSD: 262, duration: 4, durationUnit: "Days", groupSize: 20, rating: 4.6, reviewCount: 142, images: ["/images_v2/tour-beach-v2.jpg", "/images_v2/unsplash-11-v2.jpg"], amenities: ["Beach Resort", "Breakfast", "Airport Transfer", "Snorkeling Gear"], included: ["Hotel", "Meals", "Transfers", "Water activities"], excluded: ["Flights", "Visa fees", "Spa treatments"], featured: true, status: "active" },
    { title: "Golden Rock Pilgrimage", slug: "golden-rock-pilgrimage", destination: "Kyaiktiyo", description: "Journey to the sacred Golden Rock Pagoda, perched dramatically on a cliff edge. A spiritual adventure through Mon State.", priceMMK: 220000, priceUSD: 105, duration: 2, durationUnit: "Days", groupSize: 10, rating: 4.4, reviewCount: 98, images: ["/images_v2/tour-grand-v2.jpg", "/images_v2/unsplash-12-v2.jpg"], amenities: ["AC Transport", "Guide", "Breakfast", "Truck Ride"], included: ["Hotel", "Meals", "Guide", "Transport"], excluded: ["Flights", "Visa fees", "Offerings"], featured: false, status: "active" },
    { title: "Mrauk U Ancient Kingdom", slug: "mrauk-u-ancient-kingdom", destination: "Mrauk U", description: "Step back in time at the magnificent archaeological site of Mrauk U. Fortress temples, stone carvings, and Chin village visits.", priceMMK: 480000, priceUSD: 229, duration: 5, durationUnit: "Days", groupSize: 8, rating: 4.5, reviewCount: 74, images: ["/images_v2/tour-yangon-v2.jpg", "/images_v2/unsplash-6-v2.jpg"], amenities: ["AC Transport", "Guide", "Breakfast", "Village Visits"], included: ["Hotel", "Meals", "Guide", "Boat tour"], excluded: ["Flights", "Visa fees", "Tattoo face visits"], featured: false, status: "active" },
    { title: "Pyin Oo Lwin Hill Station", slug: "pyin-oo-lwin-hill-station", destination: "Pyin Oo Lwin", description: "Escape to the cool British-era hill station. Botanical gardens, strawberry farms, colonial mansions, and waterfall hikes.", priceMMK: 280000, priceUSD: 134, duration: 3, durationUnit: "Days", groupSize: 12, rating: 4.3, reviewCount: 86, images: ["/images_v2/tour-bagan-v2.jpg", "/images_v2/unsplash-7-v2.jpg"], amenities: ["AC Transport", "Guide", "Breakfast", "Horse Cart"], included: ["Hotel", "Meals", "Guide", "Garden entry"], excluded: ["Flights", "Visa fees", "Coffee purchases"], featured: false, status: "active" },
    { title: "Mergui Archipelago Adventure", slug: "mergui-archipelago-adventure", destination: "Myeik", description: "Sail through the pristine Mergui Archipelago with 800+ untouched islands. Kayaking, diving, and encounters with Moken sea gypsies.", priceMMK: 950000, priceUSD: 452, duration: 6, durationUnit: "Days", groupSize: 8, rating: 4.9, reviewCount: 53, images: ["/images_v2/tour-mandalay-v2.jpg", "/images_v2/unsplash-8-v2.jpg"], amenities: ["Private Boat", "Diving Gear", "Guide", "All Meals"], included: ["Boat cabin", "Meals", "Guide", "Water sports"], excluded: ["Flights", "Visa fees", "Diving certification"], featured: true, status: "active" },
    { title: "Hpa An Cave Explorer", slug: "hpa-an-cave-explorer", destination: "Hpa An", description: "Explore mystical limestone caves, climb Mount Zwegabin, and cruise the Thanlwin River through stunning karst landscapes.", priceMMK: 290000, priceUSD: 138, duration: 3, durationUnit: "Days", groupSize: 10, rating: 4.5, reviewCount: 91, images: ["/images_v2/tour-inle-v2.jpg", "/images_v2/unsplash-9-v2.jpg"], amenities: ["AC Transport", "Guide", "Breakfast", "Boat Ride"], included: ["Hotel", "Meals", "Guide", "Cave entries"], excluded: ["Flights", "Visa fees", "Climbing gear"], featured: false, status: "active" },
    { title: "Grand Myanmar Circuit", slug: "grand-myanmar-circuit", destination: "Myanmar", description: "The ultimate 12-day journey across Myanmar. Yangon to Bagan to Mandalay to Inle Lake to Ngapali. The complete golden land experience.", priceMMK: 1200000, priceUSD: 571, duration: 12, durationUnit: "Days", groupSize: 10, rating: 4.9, reviewCount: 312, images: ["/images_v2/tour-grand-v2.jpg", "/images_v2/unsplash-11-v2.jpg"], amenities: ["AC Transport", "English Guide", "All Meals", "Domestic Flights"], included: ["Hotels", "Meals", "Guide", "Transport", "Domestic flights", "Balloon ride"], excluded: ["International flights", "Visa fees", "Personal expenses"], featured: true, status: "active" },
    { title: "Kalaw Trekking Experience", slug: "kalaw-trekking-experience", destination: "Kalaw", description: "Trek through pine forests, tea plantations, and ethnic villages from Kalaw to Inle Lake. Authentic hill tribe encounters await.", priceMMK: 340000, priceUSD: 162, duration: 3, durationUnit: "Days", groupSize: 8, rating: 4.7, reviewCount: 143, images: ["/images_v2/tour-beach-v2.jpg", "/images_v2/unsplash-12-v2.jpg"], amenities: ["Trekking Guide", "Breakfast", "Lunch", "Village Stays"], included: ["Guide", "Meals", "Village homestay", "Transport to Inle"], excluded: ["Flights", "Visa fees", "Tips for guides"], featured: true, status: "active" },
  ],

  hotels: [
    { name: "Sule Shangri-La Yangon", slug: "sule-shangri-la-yangon", location: "Yangon", description: "Luxury 5-star hotel in downtown Yangon with panoramic city views, next to Sule Pagoda. World-class dining and butler service.", rating: 5, reviewCount: 482, pricePerNightMMK: 180000, pricePerNightUSD: 86, availableRooms: 20, totalRooms: 280, amenities: ["Pool", "WiFi", "Gym", "Spa", "Restaurant", "Bar"], images: ["/images_v2/hotel1-v3.jpg", "/images_v2/hotel-budget-v2.jpg"], status: "active", featured: true, address: "223 Sule Pagoda Road, Kyauktada Township", phone: "01-242828", email: "reservations.sule@shangri-la.com" },
    { name: "Aureum Palace Bagan", slug: "aureum-palace-bagan", location: "Bagan", description: "Boutique luxury resort nestled among ancient pagodas. Private villas, infinity pool overlooking temple plains, and traditional spa treatments.", rating: 5, reviewCount: 367, pricePerNightMMK: 220000, pricePerNightUSD: 105, availableRooms: 15, totalRooms: 110, amenities: ["Pool", "WiFi", "Spa", "Restaurant", "Bar", "Temple View"], images: ["/images_v2/hotel2-v3.jpg", "/images_v2/hotel-city-v2.jpg"], status: "active", featured: true, address: "Hotel Zone, Bagan, Mandalay Region", phone: "061-60525", email: "reservations@aureumpalacebagan.com" },
    { name: "Inle Princess Resort", slug: "inle-princess-resort", location: "Inle Lake", description: "Eco-friendly floating resort on Inle Lake. Traditional architecture meets modern comfort. Lakeside dining and sunset boat excursions.", rating: 4, reviewCount: 243, pricePerNightMMK: 160000, pricePerNightUSD: 76, availableRooms: 25, totalRooms: 50, amenities: ["Pool", "WiFi", "Spa", "Lake View", "Restaurant", "Boat Service"], images: ["/images_v2/hotel3-v3.jpg", "/images_v2/hotel-luxury-v2.jpg"], status: "active", featured: true, address: "Nyaung Shwe, Inle Lake, Shan State", phone: "081-209055", email: "info@inleprincessresort.com" },
    { name: "Ngapali Bay Hotel", slug: "ngapali-bay-hotel", location: "Ngapali Beach", description: "Beachfront resort with stunning sunset views over the Bay of Bengal. Private beach access, seafood grill, and water sports center.", rating: 4, reviewCount: 198, pricePerNightMMK: 250000, pricePerNightUSD: 119, availableRooms: 40, totalRooms: 80, amenities: ["Pool", "WiFi", "Beach Access", "Spa", "Restaurant", "Diving Center"], images: ["/images_v2/hotel4-v3.jpg", "/images_v2/hotel-resort-v2.jpg"], status: "active", featured: true, address: "Ngapali Beach, Rakhine State", phone: "043-42345", email: "reservations@ngapalibayhotel.com" },
    { name: "Mandalay Hill Resort", slug: "mandalay-hill-resort", location: "Mandalay", description: "Hilltop resort with panoramic views of Mandalay city and the Irrawaddy River. Traditional Myanmar architecture, pool, and sunset terrace.", rating: 4, reviewCount: 215, pricePerNightMMK: 120000, pricePerNightUSD: 57, availableRooms: 55, totalRooms: 200, amenities: ["Pool", "WiFi", "Gym", "Hill View", "Restaurant", "Bar"], images: ["/images_v2/hotel5-v3.jpg", "/images_v2/hotel-budget-v2.jpg"], status: "active", featured: true, address: "Near Mandalay Hill, Mandalay", phone: "02-35638", email: "info@mandalayhillresort.com" },
    { name: "The Strand Yangon", slug: "the-strand-yangon", location: "Yangon", description: "Historic colonial-era luxury hotel dating to 1901. Butler service, fine dining, and timeless elegance in the heart of Yangon.", rating: 5, reviewCount: 521, pricePerNightMMK: 350000, pricePerNightUSD: 167, availableRooms: 8, totalRooms: 32, amenities: ["Butler", "Spa", "Fine Dining", "Bar", "WiFi", "Concierge"], images: ["/images_v2/hotel6-v3.jpg", "/images_v2/hotel-luxury-v2.jpg"], status: "active", featured: true, address: "92 Strand Road, Kyauktada Township, Yangon", phone: "01-243377", email: "reservations@thestrand.com.mm" },
    { name: "Novotel Yangon Max", slug: "novotel-yangon-max", location: "Yangon", description: "Modern business hotel in Yangon's commercial district. Rooftop pool, fitness center, and multiple dining options near shopping malls.", rating: 4, reviewCount: 176, pricePerNightMMK: 145000, pricePerNightUSD: 69, availableRooms: 60, totalRooms: 250, amenities: ["Pool", "WiFi", "Gym", "Restaurant", "Bar", "Business Center"], images: ["/images_v2/hotel1-v3.jpg", "/images_v2/hotel-city-v2.jpg"], status: "active", featured: false, address: "459 Pyay Road, Kamayut Township, Yangon", phone: "01-2305858", email: "H9463@accor.com" },
    { name: "Bagan Lodge", slug: "bagan-lodge", location: "Bagan", description: "Safari-style luxury lodge with spacious tented villas. Two pools, spa, and authentic Burmese cuisine surrounded by ancient temples.", rating: 4, reviewCount: 152, pricePerNightMMK: 195000, pricePerNightUSD: 93, availableRooms: 18, totalRooms: 85, amenities: ["Pool", "WiFi", "Spa", "Restaurant", "Bar", "Garden"], images: ["/images_v2/hotel2-v3.jpg", "/images_v2/hotel-resort-v2.jpg"], status: "active", featured: false, address: "Bagan-Nyaung U Airport Road, Bagan", phone: "061-60999", email: "info@baganlodge.com" },
    { name: "Sanctum Inle Resort", slug: "sanctum-inle-resort", location: "Inle Lake", description: "Monastery-inspired luxury resort with monastery-style architecture. Infinity pool, organic gardens, lake views, and silent retreats.", rating: 5, reviewCount: 89, pricePerNightMMK: 280000, pricePerNightUSD: 133, availableRooms: 12, totalRooms: 42, amenities: ["Pool", "WiFi", "Spa", "Lake View", "Restaurant", "Yoga"], images: ["/images_v2/hotel3-v3.jpg", "/images_v2/hotel-luxury-v2.jpg"], status: "active", featured: false, address: "Maing Thauk Village, Inle Lake, Shan State", phone: "081-209266", email: "info@sanctum-inle.com" },
    { name: "Amazing Ngapali Resort", slug: "amazing-ngapali-resort", location: "Ngapali Beach", description: "Beachfront boutique resort with tropical gardens. Thatched roof bungalows, beach bar, and fresh seafood daily.", rating: 4, reviewCount: 134, pricePerNightMMK: 210000, pricePerNightUSD: 100, availableRooms: 22, totalRooms: 45, amenities: ["Pool", "WiFi", "Beach Access", "Restaurant", "Bar", "Garden"], images: ["/images_v2/hotel4-v3.jpg", "/images_v2/hotel-resort-v2.jpg"], status: "active", featured: false, address: "Zee Phyu Gone Village, Ngapali Beach", phone: "043-42266", email: "info@amazingngapali.com" },
    { name: "Eastern Palace Mandalay", slug: "eastern-palace-mandalay", location: "Mandalay", description: "Boutique hotel blending traditional Myanmar craftsmanship with contemporary luxury. Great location for exploring Mandalay's royal heritage.", rating: 3, reviewCount: 88, pricePerNightMMK: 85000, pricePerNightUSD: 40, availableRooms: 35, totalRooms: 120, amenities: ["WiFi", "Restaurant", "Bar", "Concierge", "Laundry", "Parking"], images: ["/images_v2/hotel5-v3.jpg", "/images_v2/hotel-budget-v2.jpg"], status: "active", featured: false, address: "68th Street, Between 26th and 27th, Mandalay", phone: "02-68268", email: "info@easternpalace.com.mm" },
    { name: "Chatrium Hotel Yangon", slug: "chatrium-hotel-yangon", location: "Yangon", description: "Riverside luxury near Shwedagon Pagoda. Spacious suites, infinity pool, and breathtaking views of Yangon's golden skyline.", rating: 5, reviewCount: 312, pricePerNightMMK: 205000, pricePerNightUSD: 98, availableRooms: 30, totalRooms: 200, amenities: ["Pool", "WiFi", "Gym", "Spa", "Restaurant", "River View"], images: ["/images_v2/hotel6-v3.jpg", "/images_v2/hotel-city-v2.jpg"], status: "active", featured: true, address: "40 Natmauk Road, Tamwe Township, Yangon", phone: "01-544500", email: "info@chatrium.com" },
  ],

  cars: [
    { carType: "Toyota Alphard", description: "Premium luxury MPV perfect for VIP transfers and family travel. Spacious interior with reclining leather seats.", capacity: 7, seats: 7, transmission: "Automatic", features: ["AC", "Leather Seats", "WiFi", "USB Charging", "Entertainment System"], pricingWithDriver: [{ duration: "Full Day (8 hrs)", priceMMK: 150000, priceUSD: 71 }, { duration: "Half Day (4 hrs)", priceMMK: 90000, priceUSD: 43 }, { duration: "Airport Transfer", priceMMK: 50000, priceUSD: 24 }], images: ["/images_v2/car1-v2.jpg", "/images_v2/car2-v2.jpg"], status: "active" },
    { carType: "Toyota Wish", description: "Comfortable family wagon ideal for city tours and airport transfers. Great fuel economy and smooth ride.", capacity: 5, seats: 5, transmission: "Automatic", features: ["AC", "GPS", "USB Charging", "Bluetooth", "Power Windows"], pricingWithDriver: [{ duration: "Full Day (8 hrs)", priceMMK: 80000, priceUSD: 38 }, { duration: "Half Day (4 hrs)", priceMMK: 50000, priceUSD: 24 }, { duration: "Airport Transfer", priceMMK: 30000, priceUSD: 14 }], images: ["/images_v2/car3-v2.jpg", "/images_v2/car4-v2.jpg"], status: "active" },
    { carType: "Toyota Hiace", description: "Spacious group transport van for large families or tour groups. Ample luggage space for long journeys.", capacity: 12, seats: 12, transmission: "Manual", features: ["AC", "Luggage Space", "USB Charging", "Roof Rack", "Power Steering"], pricingWithDriver: [{ duration: "Full Day (8 hrs)", priceMMK: 120000, priceUSD: 57 }, { duration: "Half Day (4 hrs)", priceMMK: 75000, priceUSD: 36 }, { duration: "Airport Transfer", priceMMK: 45000, priceUSD: 21 }], images: ["/images_v2/car5-v2.jpg", "/images_v2/car6-v2.jpg"], status: "active" },
    { carType: "Honda CR-V", description: "Capable SUV for both city and rough terrain. Comfortable for long drives with excellent ground clearance.", capacity: 5, seats: 5, transmission: "Automatic", features: ["AC", "4WD", "Sunroof", "GPS", "Bluetooth", "Leather Seats"], pricingWithDriver: [{ duration: "Full Day (8 hrs)", priceMMK: 95000, priceUSD: 45 }, { duration: "Half Day (4 hrs)", priceMMK: 60000, priceUSD: 29 }, { duration: "Airport Transfer", priceMMK: 35000, priceUSD: 17 }], images: ["/images_v2/car1-v2.jpg", "/images_v2/car2-v2.jpg"], status: "active" },
    { carType: "Mercedes S-Class", description: "Ultimate executive luxury sedan for VIPs and business travelers. Massage seats and premium sound system.", capacity: 3, seats: 3, transmission: "Automatic", features: ["AC", "WiFi", "Massage Seats", "Premium Sound", "Privacy Glass", "Mini Bar"], pricingWithDriver: [{ duration: "Full Day (8 hrs)", priceMMK: 250000, priceUSD: 119 }, { duration: "Half Day (4 hrs)", priceMMK: 160000, priceUSD: 76 }, { duration: "Airport Transfer", priceMMK: 80000, priceUSD: 38 }], images: ["/images_v2/car3-v2.jpg", "/images_v2/car4-v2.jpg"], status: "active" },
    { carType: "Toyota Land Cruiser Prado", description: "Powerful off-road SUV for adventure trips and rough terrain. 7-seater with excellent safety features.", capacity: 7, seats: 7, transmission: "Automatic", features: ["AC", "4WD", "Roof Rack", "GPS", "Bluetooth", "Leather Seats"], pricingWithDriver: [{ duration: "Full Day (8 hrs)", priceMMK: 180000, priceUSD: 86 }, { duration: "Half Day (4 hrs)", priceMMK: 110000, priceUSD: 52 }, { duration: "Airport Transfer", priceMMK: 60000, priceUSD: 29 }], images: ["/images_v2/car5-v2.jpg", "/images_v2/car6-v2.jpg"], status: "active" },
    { carType: "Toyota Probox", description: "Budget-friendly wagon for city runs and quick transfers. Practical and fuel-efficient for short trips.", capacity: 5, seats: 5, transmission: "Automatic", features: ["AC", "Power Windows", "USB Charging", "Bluetooth"], pricingWithDriver: [{ duration: "Full Day (8 hrs)", priceMMK: 55000, priceUSD: 26 }, { duration: "Half Day (4 hrs)", priceMMK: 35000, priceUSD: 17 }, { duration: "Airport Transfer", priceMMK: 20000, priceUSD: 10 }], images: ["/images_v2/car1-v2.jpg", "/images_v2/car2-v2.jpg"], status: "active" },
    { carType: "Mazda CX-5", description: "Stylish crossover SUV with premium interior. Great handling for Myanmar roads with comfort and safety.", capacity: 5, seats: 5, transmission: "Automatic", features: ["AC", "GPS", "Bluetooth", "Sunroof", "Leather Seats", "Parking Sensors"], pricingWithDriver: [{ duration: "Full Day (8 hrs)", priceMMK: 110000, priceUSD: 52 }, { duration: "Half Day (4 hrs)", priceMMK: 70000, priceUSD: 33 }, { duration: "Airport Transfer", priceMMK: 40000, priceUSD: 19 }], images: ["/images_v2/car3-v2.jpg", "/images_v2/car4-v2.jpg"], status: "active" },
    { carType: "Ford Transit", description: "Large 15-seater minibus for big groups, school trips, and corporate outings. Powerful diesel engine.", capacity: 15, seats: 15, transmission: "Manual", features: ["AC", "Luggage Space", "PA System", "Comfort Seats", "Roof Rack"], pricingWithDriver: [{ duration: "Full Day (8 hrs)", priceMMK: 160000, priceUSD: 76 }, { duration: "Half Day (4 hrs)", priceMMK: 100000, priceUSD: 48 }, { duration: "Airport Transfer", priceMMK: 55000, priceUSD: 26 }], images: ["/images_v2/car5-v2.jpg", "/images_v2/car6-v2.jpg"], status: "active" },
    { carType: "Nissan X-Trail", description: "Versatile SUV perfect for family adventures. Spacious cargo area and comfortable for long-distance journeys.", capacity: 5, seats: 5, transmission: "Automatic", features: ["AC", "4WD", "GPS", "Bluetooth", "Power Windows"], pricingWithDriver: [{ duration: "Full Day (8 hrs)", priceMMK: 100000, priceUSD: 48 }, { duration: "Half Day (4 hrs)", priceMMK: 65000, priceUSD: 31 }, { duration: "Airport Transfer", priceMMK: 38000, priceUSD: 18 }], images: ["/images_v2/car1-v2.jpg", "/images_v2/car2-v2.jpg"], status: "active" },
    { carType: "BMW 7 Series", description: "Flagship luxury sedan with cutting-edge technology. Executive lounge seating with panoramic glass roof.", capacity: 3, seats: 3, transmission: "Automatic", features: ["AC", "WiFi", "Massage Seats", "Ambient Lighting", "Privacy Glass", "Premium Sound"], pricingWithDriver: [{ duration: "Full Day (8 hrs)", priceMMK: 280000, priceUSD: 133 }, { duration: "Half Day (4 hrs)", priceMMK: 180000, priceUSD: 86 }, { duration: "Airport Transfer", priceMMK: 95000, priceUSD: 45 }], images: ["/images_v2/car3-v2.jpg", "/images_v2/car4-v2.jpg"], status: "active" },
    { carType: "Mitsubishi Pajero", description: "Legendary off-road SUV built for Myanmar's toughest terrain. 7-seater with exceptional durability.", capacity: 7, seats: 7, transmission: "Automatic", features: ["AC", "4WD", "Roof Rack", "Winch", "Snorkel", "Heavy Duty Suspension"], pricingWithDriver: [{ duration: "Full Day (8 hrs)", priceMMK: 170000, priceUSD: 81 }, { duration: "Half Day (4 hrs)", priceMMK: 105000, priceUSD: 50 }, { duration: "Airport Transfer", priceMMK: 55000, priceUSD: 26 }], images: ["/images_v2/car5-v2.jpg", "/images_v2/car6-v2.jpg"], status: "active" },
  ],

  visas: [
    { country: "Thailand", countryCode: "TH", processingTime: "3-5 Working Days", visaFeeMMK: 60000, visaFeeUSD: 29, requirements: ["Valid passport 6+ months", "2 passport photos", "Bank statement", "Flight itinerary", "Hotel booking"], additionalInfo: "eVisa available for eligible nationalities. Free visa-on-arrival for some countries.", image: "/images_v2/visa-thailand-v2.jpg" },
    { country: "Singapore", countryCode: "SG", processingTime: "3 Working Days", visaFeeMMK: 45000, visaFeeUSD: 21, requirements: ["Valid passport 6+ months", "2 passport photos", "Hotel booking", "Flight itinerary", "Bank statement"], additionalInfo: "eVisa available. Single entry, valid for 30 days.", image: "/images_v2/visa-singapore-v2.jpg" },
    { country: "China", countryCode: "CN", processingTime: "4-6 Working Days", visaFeeMMK: 55000, visaFeeUSD: 26, requirements: ["Valid passport 6+ months", "2 passport photos", "Invitation letter or hotel booking", "Flight itinerary", "Bank statement"], additionalInfo: "Single/Double entry available. Tourist (L) visa valid for 30 days.", image: "/images_v2/visa-china-v2.jpg" },
    { country: "India", countryCode: "IN", processingTime: "5-7 Working Days", visaFeeMMK: 65000, visaFeeUSD: 31, requirements: ["Valid passport 6+ months", "2 passport photos", "Flight itinerary", "Hotel booking", "Bank statement"], additionalInfo: "eVisa available for tourism. Single/Double entry options.", image: "/images_v2/visa-india-v2.jpg" },
    { country: "Malaysia", countryCode: "MY", processingTime: "2-3 Working Days", visaFeeMMK: 30000, visaFeeUSD: 14, requirements: ["Valid passport 6+ months", "2 passport photos", "Flight itinerary", "Hotel booking"], additionalInfo: "eVisa available. Visa-free for ASEAN nationals.", image: "/images_v2/visa-malaysia-v2.jpg" },
    { country: "UAE (Dubai)", countryCode: "AE", processingTime: "3-4 Working Days", visaFeeMMK: 85000, visaFeeUSD: 40, requirements: ["Valid passport 6+ months", "2 passport photos", "Flight itinerary", "Hotel booking", "Bank statement"], additionalInfo: "30-day tourist visa. Express processing available at extra cost.", image: "/images_v2/visa-uae-v2.jpg" },
    { country: "Japan", countryCode: "JP", processingTime: "7-10 Working Days", visaFeeMMK: 80000, visaFeeUSD: 38, requirements: ["Valid passport 6+ months", "2 passport photos", "Bank statement", "Detailed itinerary", "Employment letter"], additionalInfo: "Single/Multiple entry available. Requires in-person interview in some cases.", image: "/images_v2/visa1-v3.jpg" },
    { country: "South Korea", countryCode: "KR", processingTime: "5-7 Working Days", visaFeeMMK: 70000, visaFeeUSD: 33, requirements: ["Valid passport 6+ months", "2 passport photos", "Bank statement", "Flight itinerary", "Hotel booking"], additionalInfo: "K-ETA available for eligible nationalities. Tourist visa valid for 90 days.", image: "/images_v2/visa2-v3.jpg" },
    { country: "Vietnam", countryCode: "VN", processingTime: "3-5 Working Days", visaFeeMMK: 40000, visaFeeUSD: 19, requirements: ["Valid passport 6+ months", "2 passport photos", "Flight itinerary"], additionalInfo: "eVisa available. Visa-free for 30 days for select ASEAN nationals.", image: "/images_v2/visa3-v3.jpg" },
    { country: "Cambodia", countryCode: "KH", processingTime: "2-3 Working Days", visaFeeMMK: 35000, visaFeeUSD: 17, requirements: ["Valid passport 6+ months", "2 passport photos", "Flight itinerary"], additionalInfo: "eVisa and visa-on-arrival available. Valid for 30 days.", image: "/images_v2/visa4-v3.jpg" },
    { country: "Australia", countryCode: "AU", processingTime: "10-15 Working Days", visaFeeMMK: 120000, visaFeeUSD: 57, requirements: ["Valid passport 6+ months", "2 passport photos", "Bank statement 6 months", "Employment letter", "Travel itinerary", "Health insurance"], additionalInfo: "Electronic Travel Authority (ETA) for eligible passports. Tourist visa valid 3-12 months.", image: "/images_v2/visa5-v3.jpg" },
    { country: "Turkey", countryCode: "TR", processingTime: "5-7 Working Days", visaFeeMMK: 75000, visaFeeUSD: 36, requirements: ["Valid passport 6+ months", "2 passport photos", "Bank statement", "Flight itinerary", "Hotel booking", "Travel insurance"], additionalInfo: "eVisa available online. Multiple-entry tourist visa for 90 days.", image: "/images_v2/visa6-v3.jpg" },
  ],

  insurances: [
    { planName: "Basic Travel Shield", title: "Essential Protection", coverage: "Medical Emergency + Trip Delay", duration: "Per Trip (Up to 30 days)", priceMMK: 15000, priceUSD: 7, benefits: ["Medical emergency up to 5,000,000 MMK", "Trip delay compensation", "Lost baggage coverage", "24/7 emergency hotline", "Emergency dental care"], description: "Affordable essential coverage for short trips. Covers medical emergencies and common travel disruptions.", image: "/images_v2/ins1-v3.jpg" },
    { planName: "Standard Travel Guard", title: "Comprehensive Protection", coverage: "Medical + Baggage + Cancellation", duration: "Per Trip (Up to 60 days)", priceMMK: 25000, priceUSD: 12, benefits: ["Medical emergency up to 10,000,000 MMK", "Baggage loss/delay", "Trip cancellation", "Flight delay compensation", "Emergency evacuation", "24/7 support"], description: "Comprehensive protection for longer trips. Covers medical, baggage, and trip disruptions.", image: "/images_v2/ins2-v3.jpg" },
    { planName: "Premium Travel Protect", title: "Ultimate Peace of Mind", coverage: "Full Medical + Cancellation + Concierge", duration: "Annual (Unlimited trips)", priceMMK: 45000, priceUSD: 21, benefits: ["Unlimited medical coverage up to 50,000,000 MMK", "Trip cancellation - any reason", "Concierge service", "Personal liability", "Rental car excess", "Premium airport lounge access"], description: "Premium travel insurance for frequent travelers. Annual coverage with unlimited trips worldwide.", image: "/images_v2/ins3-v3.jpg" },
    { planName: "Family Travel Plan", title: "Family Protection Bundle", coverage: "Family Medical + Trip Protection", duration: "Per Trip (Up to 30 days)", priceMMK: 60000, priceUSD: 29, benefits: ["Full family medical coverage up to 20,000,000 MMK", "Child medical cover", "Family trip cancellation", "Stroller/luggage loss", "Emergency child care", "Family reunion cover"], description: "Complete family protection covering parents and up to 4 children under one affordable plan.", image: "/images_v2/ins4-v3.jpg" },
    { planName: "Senior Travel Cover", title: "Senior Travelers Plan", coverage: "Medical + Evacuation + Repatriation", duration: "Per Trip (Up to 45 days)", priceMMK: 55000, priceUSD: 26, benefits: ["Medical emergency up to 30,000,000 MMK", "Emergency medical evacuation", "Repatriation cover", "Hospital cash benefit", "Companion travel cover", "Pre-existing condition review"], description: "Specialized coverage for travelers aged 60-85 with comprehensive medical protection.", image: "/images_v2/ins1-v3.jpg" },
    { planName: "Adventure Sports Pack", title: "Extreme Coverage", coverage: "Sports Injury + Rescue + Equipment", duration: "Per Trip (Up to 30 days)", priceMMK: 85000, priceUSD: 40, benefits: ["Sports injury medical up to 35,000,000 MMK", "Helicopter/mountain rescue", "Equipment loss/damage", "Search and rescue", "Activity cancellation", "Accidental death and disability"], description: "For thrill-seekers. Covers scuba diving, trekking, rock climbing, and 50+ adventure activities.", image: "/images_v2/ins2-v3.jpg" },
    { planName: "Business Travel Pro", title: "Corporate Travel Plan", coverage: "Medical + Productivity Protection", duration: "Annual (Unlimited trips)", priceMMK: 75000, priceUSD: 36, benefits: ["Medical emergency up to 40,000,000 MMK", "Business equipment cover", "Document replacement", "Missed meeting coverage", "Productivity loss compensation", "VIP airport assistance"], description: "Tailored for business travelers. Covers equipment, documents, and professional disruptions.", image: "/images_v2/ins3-v3.jpg" },
    { planName: "Student Travel Basic", title: "Student Budget Plan", coverage: "Medical + Baggage + Study Interruption", duration: "Per Trip (Up to 6 months)", priceMMK: 12000, priceUSD: 6, benefits: ["Medical emergency up to 3,000,000 MMK", "Baggage loss/theft", "Study interruption cover", "Emergency family visit", "Personal liability", "24/7 counseling hotline"], description: "Affordable coverage designed for students studying abroad or traveling on a budget.", image: "/images_v2/ins4-v3.jpg" },
    { planName: "Cruise Coverage Plan", title: "Cruise Protection", coverage: "Medical + Missed Port + Cabin Cover", duration: "Per Cruise", priceMMK: 95000, priceUSD: 45, benefits: ["Medical emergency up to 60,000,000 MMK", "Missed port departure", "Cabin confinement cover", "Itinerary change compensation", "Shore excursion cover", "Cruise interruption"], description: "Specialized cruise travel insurance. Covers medical emergencies at sea and missed port departures.", image: "/images_v2/ins1-v3.jpg" },
    { planName: "Gold Travel Elite", title: "VIP Protection", coverage: "All-Inclusive Medical + Luxury Benefits", duration: "Annual (Unlimited trips)", priceMMK: 150000, priceUSD: 71, benefits: ["Unlimited medical coverage up to 100,000,000 MMK", "Private jet evacuation", "Personal assistant", "5-star hospital cash", "Lost passport service", "Cancel for any reason", "Golf equipment cover"], description: "Ultimate VIP travel insurance. Unlimited medical, private evacuation, and luxury concierge service.", image: "/images_v2/ins2-v3.jpg" },
    { planName: "Domestic Travel Care", title: "Myanmar Domestic Plan", coverage: "Domestic Medical + Trip Protection", duration: "Per Trip (Up to 15 days)", priceMMK: 8000, priceUSD: 4, benefits: ["Medical emergency up to 2,000,000 MMK", "Trip cancellation", "Lost baggage", "Flight delay", "Emergency transport", "24/7 local support"], description: "Affordable domestic travel insurance for trips within Myanmar. Quick claims processing.", image: "/images_v2/ins3-v3.jpg" },
    { planName: "Schengen Travel Cover", title: "Europe Schengen Plan", coverage: "Medical (Schengen Compliant) + Travel", duration: "Per Trip (Up to 90 days)", priceMMK: 70000, priceUSD: 33, benefits: ["Medical emergency up to 50,000,000 MMK (EUR 50,000 min)", "Trip cancellation", "Lost passport and documents", "Flight delay compensation", "Emergency evacuation", "Schengen-compliant certificate"], description: "Schengen visa-compliant travel insurance meeting all European embassy requirements for visa applications.", image: "/images_v2/ins4-v3.jpg" },
  ],

  cruises: [
    { title: "Halong Bay Luxury Cruise", destination: "Vietnam", description: "Sail through the emerald waters of Halong Bay aboard a traditional junk boat. Kayaking, cave explorations, and sunset squid fishing.", priceMMK: 650000, priceUSD: 310, duration: "3 Days / 2 Nights", images: ["/images_v2/hero-cruises-v2.jpg", "/images_v2/hero-vietnam-v2.jpg"] },
    { title: "Singapore Harbor Cruise", destination: "Singapore", description: "Luxury cruise around Singapore's stunning skyline. Marina Bay Sands views, Sentosa Island, and gourmet dining at sea.", priceMMK: 800000, priceUSD: 381, duration: "4 Days / 3 Nights", images: ["/images_v2/hero-singapore-v2.jpg", "/images_v2/hero-cambodia-v2.jpg"] },
    { title: "Phuket Island Hopper", destination: "Thailand", description: "Island-hopping cruise around Phuket, Phi Phi, and James Bond Island. Snorkeling, beach BBQs, and stunning sunsets.", priceMMK: 950000, priceUSD: 452, duration: "5 Days / 4 Nights", images: ["/images_v2/hero-thailand-v2.jpg", "/images_v2/hero-china-v2.jpg"] },
    { title: "Mekong River Journey", destination: "Cambodia/Vietnam", description: "Scenic river cruise along the mighty Mekong. Floating markets, ancient temples, and remote village visits through two countries.", priceMMK: 550000, priceUSD: 262, duration: "5 Days / 4 Nights", images: ["/images_v2/hero-cambodia-v2.jpg", "/images_v2/hero-vietnam-v2.jpg"] },
    { title: "Bali Sunset Cruise", destination: "Indonesia", description: "Romantic sunset cruise around Bali's coast. Live music, candlelit dinner, and views of volcanic landscapes from the sea.", priceMMK: 550000, priceUSD: 262, duration: "3 Days / 2 Nights", images: ["/images_v2/hero-indonesia-v2.jpg", "/images_v2/hero-malaysia-v2.jpg"] },
    { title: "Mediterranean Dream", destination: "Greece/Italy", description: "Luxury Mediterranean cruise through Greek islands and Italian coast. Ancient ruins, turquoise waters, and world-class cuisine.", priceMMK: 2500000, priceUSD: 1190, duration: "7 Days / 6 Nights", images: ["/images_v2/hero-cruises-v2.jpg", "/images_v2/hero-philippines-v2.jpg"] },
    { title: "Dubai Marina Dhow Cruise", destination: "UAE", description: "Evening dhow cruise along Dubai Marina. Stunning skyline views, international buffet dinner, and live entertainment under the stars.", priceMMK: 350000, priceUSD: 167, duration: "1 Day", images: ["/images_v2/hero-china-v2.jpg", "/images_v2/unsplash-18-v2.jpg"] },
    { title: "Maldives Overwater Cruise", destination: "Maldives", description: "Ultimate luxury cruise through Maldives atolls. Overwater villas, private island visits, and world-class diving with whale sharks.", priceMMK: 3200000, priceUSD: 1524, duration: "6 Days / 5 Nights", images: ["/images_v2/hero-malaysia-v2.jpg", "/images_v2/unsplash-20-v2.jpg"] },
    { title: "Yangon River Sunset Cruise", destination: "Myanmar", description: "Traditional river cruise along Yangon River. Watch the sunset over Shwedagon Pagoda with local snacks and traditional music.", priceMMK: 120000, priceUSD: 57, duration: "Half Day", images: ["/images_v2/hero-cruises-v2.jpg", "/images_v2/unsplash-21-v2.jpg"] },
    { title: "Caribbean Explorer", destination: "Caribbean", description: "Ultimate Caribbean island-hopping adventure. White sand beaches, reggae rhythms, and crystal-clear snorkeling waters.", priceMMK: 4200000, priceUSD: 2000, duration: "10 Days / 9 Nights", images: ["/images_v2/hero-philippines-v2.jpg", "/images_v2/unsplash-18-v2.jpg"] },
    { title: "Bagan Irrawaddy Cruise", destination: "Myanmar", description: "Luxury Irrawaddy river cruise from Bagan to Mandalay. Ancient pagodas, riverside villages, and spectacular sunrises.", priceMMK: 480000, priceUSD: 229, duration: "4 Days / 3 Nights", images: ["/images_v2/hero-vietnam-v2.jpg", "/images_v2/unsplash-20-v2.jpg"] },
    { title: "Komodo Island Expedition", destination: "Indonesia", description: "Expedition cruise to Komodo National Park. See Komodo dragons, pink beaches, and world-class diving spots.", priceMMK: 1800000, priceUSD: 857, duration: "5 Days / 4 Nights", images: ["/images_v2/hero-indonesia-v2.jpg", "/images_v2/unsplash-21-v2.jpg"] },
  ],

  mingalar: [
    { title: "Fine Dining", desc: "Premium international buffet and a la carte menu with live cooking stations", icon: "🍽️", img: "/images_v2/sky1-v3.jpg" },
    { title: "Open Bar", desc: "Complimentary premium drinks, cocktails, wines and spirits served all day", icon: "🍸", img: "/images_v2/sky2-v3.jpg" },
    { title: "Workspace", desc: "High-speed WiFi, quiet workstations, printing and business center facilities", icon: "💻", img: "/images_v2/sky3-v3.jpg" },
    { title: "Shower Suites", desc: "Refresh with private shower suites, premium toiletries and towel service", icon: "🚿", img: "/images_v2/sky1-v3.jpg" },
    { title: "Nap Pods", desc: "Rest in private sleeping pods with blackout curtains and noise cancellation", icon: "😴", img: "/images_v2/sky2-v3.jpg" },
    { title: "Concierge", desc: "Priority check-in, boarding assistance and personalized travel concierge", icon: "🛎️", img: "/images_v2/sky3-v3.jpg" },
    { title: "Spa and Wellness", desc: "Massage chairs, aromatherapy and express spa treatments before your flight", icon: "💆", img: "/images_v2/sky1-v3.jpg" },
    { title: "Cinema Room", desc: "Private cinema screening latest movies with surround sound and recliners", icon: "🎬", img: "/images_v2/sky2-v3.jpg" },
    { title: "Kids Zone", desc: "Safe, supervised play area with games, toys and activities for children", icon: "🧒", img: "/images_v2/sky3-v3.jpg" },
    { title: "Smoking Lounge", desc: "Ventilated premium smoking lounge with comfortable seating and air filtration", icon: "🚬", img: "/images_v2/sky1-v3.jpg" },
    { title: "Prayer Room", desc: "Quiet, private multi-faith prayer room with ablution facilities", icon: "🕌", img: "/images_v2/sky2-v3.jpg" },
    { title: "Flight Info", desc: "Real-time flight status displays, gate info and departure announcements", icon: "✈️", img: "/images_v2/sky3-v3.jpg" },
  ],

  blog: [
    { title: "10 Must-Visit Temples in Bagan", content: "Bagan is home to over 2,000 ancient temples scattered across a vast plain. From the iconic Ananda Temple to the towering Thatbyinnyu, each temple tells a story of Myanmar's golden age. The best way to explore is by e-bike at sunrise, when the mist rolls over the plains and hot air balloons dot the sky. Don't miss Shwezigon Pagoda, Dhammayangyi Temple, and the sunset views from Shwesandaw. Tip: Visit between November and February for the best weather and the annual balloon festival.", image: "/images_v2/blog1-v2.jpg", tags: ["Myanmar", "Temples", "Bagan", "Travel Tips"], date: "2026-07-10", author: "A9 Travel Team", excerpt: "Discover the most stunning ancient temples in Bagan, from sunrise balloon rides to hidden pagodas off the beaten path." },
    { title: "Complete Guide to Myanmar Visa Requirements", content: "Planning a trip to Myanmar? Here's everything you need to know about visa requirements. Most nationalities can apply for an eVisa online, which takes 3-5 business days. You'll need a valid passport with at least 6 months validity, a digital passport photo, and hotel booking confirmation. The tourist eVisa allows a 28-day stay. Business visas require an invitation letter. Visa-on-arrival is available for some nationalities at Yangon, Mandalay, and Nay Pyi Taw airports. Always check the latest requirements before traveling as policies can change.", image: "/images_v2/blog2-v2.jpg", tags: ["Myanmar", "Visa", "Travel Guide", "Requirements"], date: "2026-07-05", author: "A9 Visa Desk", excerpt: "Everything you need to know about Myanmar visa requirements, eVisa applications, and entry procedures for 2026." },
    { title: "Inle Lake: A Photographer's Paradise", content: "Inle Lake is one of Myanmar's most photogenic destinations. The iconic leg-rowing fishermen, floating gardens, and stilted villages offer endless photo opportunities. Visit during the Phaung Daw Oo Pagoda Festival in September/October for vibrant boat processions. The five-day rotating markets provide colorful street photography scenes. For the best shots, hire a private boat and start at dawn when the lake is calm and the light is golden. Don't forget to explore the Indein pagoda complex with its forest of ancient stupas.", image: "/images_v2/blog3-v2.jpg", tags: ["Myanmar", "Inle Lake", "Photography", "Travel"], date: "2026-06-28", author: "A9 Photography", excerpt: "Capture the magic of Inle Lake — leg-rowing fishermen, floating markets, and misty morning landscapes." },
    { title: "Top 5 Beach Destinations in Southeast Asia", content: "Southeast Asia boasts some of the world's most beautiful beaches. From Thailand's Phi Phi Islands to Myanmar's pristine Ngapali Beach, there's a beach for every type of traveler. Ngapali offers uncrowded white sand and fresh seafood. Thailand's Railay Beach is a rock-climber's dream. Vietnam's Phu Quoc combines luxury resorts with local charm. The Philippines' Palawan has been voted the world's best island multiple times. Indonesia's Bali offers surf culture, temples, and rice terraces alongside beautiful coastlines. Best time to visit: November to April for most destinations.", image: "/images_v2/blog4-v2.jpg", tags: ["Beaches", "Southeast Asia", "Thailand", "Myanmar"], date: "2026-06-20", author: "A9 Travel Team", excerpt: "From Ngapali to Palawan — the best beach destinations in Southeast Asia for sun, sand, and crystal waters." },
    { title: "Mandalay: The Last Royal Capital", content: "Mandalay, Myanmar's last royal capital, is a city rich in history and culture. Start your journey at Mandalay Palace, a reconstructed royal compound. Climb Mandalay Hill for panoramic sunset views. Visit the Mahamuni Buddha Temple, home to one of Myanmar's most revered Buddha images. Cross the iconic U Bein Bridge at Amarapura — the world's longest teak bridge. Don't miss the stone-carving workshops and gold-leaf beating demonstrations. Day trips to Mingun, Sagaing, and Inwa complete the Mandalay experience. The city is also the gateway to Pyin Oo Lwin, a charming British-era hill station.", image: "/images_v2/blog1-v2.jpg", tags: ["Myanmar", "Mandalay", "History", "Culture"], date: "2026-06-15", author: "A9 Heritage", excerpt: "Explore Mandalay — royal palaces, ancient capitals, and the world's longest teak bridge." },
    { title: "Essential Packing List for Myanmar Travel", content: "Packing right can make or break your Myanmar trip. Lightweight, modest clothing is essential — shoulders and knees should be covered when visiting temples. Comfortable walking sandals that are easy to slip off (you'll remove shoes at temples frequently). A light scarf or shawl doubles as sun protection and temple cover-up. Bring a reusable water bottle, sunscreen, insect repellent, and a power bank (power outages happen). A headlamp is useful for Bagan's dark temples. Pack a rain jacket if visiting during monsoon season (May-October). Don't forget cash — ATMs are available but can be unreliable in remote areas.", image: "/images_v2/blog2-v2.jpg", tags: ["Myanmar", "Travel Tips", "Packing", "Preparation"], date: "2026-06-08", author: "A9 Travel Tips", excerpt: "Everything you need to pack for Myanmar — from temple-appropriate clothing to essential gear." },
    { title: "Street Food Guide: Yangon's Best Eats", content: "Yangon's street food scene is legendary. Start with mohinga, Myanmar's national dish — a fish-based noodle soup served with crispy fritters. 19th Street in Chinatown comes alive at night with sizzling BBQ skewers and cold draft beer. Try laphet thoke (tea leaf salad) at Rangoon Tea House. Samosas, paratha with curry, and Shan noodles are must-try breakfast items. For dessert, don't miss shwe yin aye (coconut cream sweet soup) and mont let saung (tapioca balls in coconut milk). Head to Bogyoke Market area for the best daytime street food stalls. Always look for busy stalls with high turnover for the freshest food.", image: "/images_v2/blog3-v2.jpg", tags: ["Myanmar", "Yangon", "Food", "Street Food"], date: "2026-05-30", author: "A9 Food Guide", excerpt: "From mohinga breakfast to 19th Street BBQ — Yangon's best street food spots you can't miss." },
    { title: "Why Travel Insurance is Non-Negotiable", content: "Travel insurance isn't just a nice-to-have — it's essential. Medical emergencies abroad can cost thousands of dollars. Trip cancellations, lost baggage, and flight delays happen more often than you think. A comprehensive travel insurance plan covers medical emergencies, emergency evacuation, trip cancellation, baggage loss, and personal liability. For Myanmar specifically, consider coverage that includes helicopter rescue for remote areas. Adventure travelers should ensure their activities are covered. A9 Global Travel offers 12 comprehensive plans starting from just 8,000 MMK. Don't leave home without it — the peace of mind is worth every kyat.", image: "/images_v2/blog4-v2.jpg", tags: ["Insurance", "Travel Tips", "Safety", "Planning"], date: "2026-05-22", author: "A9 Insurance Desk", excerpt: "Why travel insurance is essential for every trip — from medical emergencies to trip cancellations." },
    { title: "Exploring Myanmar by Car: Road Trip Guide", content: "Myanmar's diverse landscapes make it perfect for road trips. Hire a car with driver through A9 Global Travel and explore at your own pace. The Yangon-Bagan-Mandalay circuit is the classic route, taking you from colonial cities to ancient temple plains. For adventurers, the road to Mrauk U in Rakhine State offers remote countryside and hill tribe encounters. The Shan State route from Kalaw to Inle Lake passes through pine forests and tea plantations. Our fleet includes SUVs for rough terrain, luxury sedans for city tours, and minibuses for group travel. All cars come with experienced English-speaking drivers who double as informal guides.", image: "/images_v2/blog1-v2.jpg", tags: ["Myanmar", "Road Trip", "Cars", "Adventure"], date: "2026-05-15", author: "A9 Road Trips", excerpt: "The ultimate Myanmar road trip guide — best routes, car options, and what to expect on the road." },
    { title: "Singapore on a Budget: Insider Tips", content: "Singapore doesn't have to break the bank. Stay in budget-friendly areas like Little India or Chinatown. Eat at hawker centers — Michelin-starred meals for under 5 SGD. Visit free attractions: Gardens by the Bay Supertree Grove light show, Botanic Gardens, and Sentosa's beaches. Use the MRT for cheap, efficient transport. Skip expensive Singapore Slings at Raffles — try a local kopi instead. The Singapore Tourist Pass offers unlimited public transport. Visit during the Great Singapore Sale (June-August) for shopping deals. With A9's budget Singapore packages starting at 250,000 MMK, the Lion City is more accessible than you think.", image: "/images_v2/blog2-v2.jpg", tags: ["Singapore", "Budget Travel", "Tips", "Asia"], date: "2026-05-08", author: "A9 Budget Travel", excerpt: "How to experience Singapore without overspending — from hawker center feasts to free attractions." },
    { title: "Best Time to Visit Thailand Month by Month", content: "Thailand's climate varies significantly by region and season. November to February is the cool, dry season — perfect for Bangkok, Chiang Mai, and the Andaman coast. March to May brings scorching heat, ideal for beach destinations and Songkran (Thai New Year) water festival in April. June to October is the rainy season, but Koh Samui and the Gulf islands stay relatively dry. The north is lush and green during rainy season, with fewer tourists and lower prices. December is peak tourist season — book early. For diving, the Andaman Sea is best November-April, while the Gulf of Thailand peaks May-September.", image: "/images_v2/blog3-v2.jpg", tags: ["Thailand", "Travel Tips", "Seasons", "Planning"], date: "2026-04-30", author: "A9 Thailand Desk", excerpt: "Month-by-month guide to the best time to visit Thailand — weather, festivals, and crowd levels." },
    { title: "Cruise vs Land Tour: Which is Right for You?", content: "Choosing between a cruise and land tour depends on your travel style. Cruises offer unpack-once convenience, all-inclusive dining, and the thrill of waking up in a new destination each day. They're great for multi-country itineraries and travelers who want everything organized. Land tours provide deeper cultural immersion, flexibility to explore at your own pace, and access to inland destinations cruise ships can't reach. For Myanmar, combine both — take an Irrawaddy cruise between Bagan and Mandalay, then explore on land. A9 Global Travel offers 12 cruise options across Southeast Asia and land tours in every major destination.", image: "/images_v2/blog4-v2.jpg", tags: ["Cruises", "Tours", "Travel Planning", "Comparison"], date: "2026-04-22", author: "A9 Cruise Desk", excerpt: "Cruise vs land tour — which travel style fits your personality, budget, and dream itinerary." },
  ],

  popularDestinations: [
    { city: "Paris", country: "France", image: "/images_v2/dest-paris-v2.jpg", minPrice: "Ks 850,000", rating: 4.8, reviews: 2340, duration: "5 Days", tags: ["Luxury", "Romance", "Culture"], description: "Wander cobblestone streets, marvel at the Eiffel Tower sparkle at night, explore world-famous art at the Louvre, and indulge in buttery croissants at charming sidewalk cafés." },
    { city: "Dubai", country: "UAE", image: "/images_v2/dest-dubai-v2.jpg", minPrice: "Ks 680,000", rating: 4.7, reviews: 1890, duration: "4 Days", tags: ["Luxury", "Shopping", "Modern"], description: "Ride to the top of Burj Khalifa, race across golden dunes in a 4x4 safari, shop glittering gold souks, and marvel at a city that rose from the desert." },
    { city: "Korea", country: "South Korea", image: "/images_v2/dest-korea-v2.jpg", minPrice: "Ks 550,000", rating: 4.6, reviews: 1560, duration: "6 Days", tags: ["Culture", "Food", "K-Pop"], description: "Walk through centuries-old Gyeongbokgung Palace, feast on sizzling Korean BBQ in Myeongdong, belt out K-pop hits at noraebang, and chase cherry blossoms along the Han River." },
    { city: "Thailand", country: "Thailand", image: "/images_v2/hero-thailand-v2.jpg", minPrice: "Ks 150,000", rating: 4.5, reviews: 3210, duration: "4 Days", tags: ["Beach", "Temple", "Food"], description: "Kneel before the glittering Grand Palace, island-hop turquoise Andaman waters, drift through Damnoen Saduak floating market at dawn, and savor spicy tom yum by lantern-lit beaches." },
    { city: "Singapore", country: "Singapore", image: "/images_v2/hero-singapore-v2.jpg", minPrice: "Ks 250,000", rating: 4.7, reviews: 1980, duration: "3 Days", tags: ["Modern", "Food", "Shopping"], description: "Gaze across the city from Marina Bay Sands SkyPark, wander Supertree Groves at dusk, devour Michelin-starred hawker chicken rice, and explore Chinatown's hidden temples and aromatic spice shops." },
    { city: "Japan", country: "Japan", image: "/images_v2/dest-japan-v2.jpg", minPrice: "Ks 780,000", rating: 4.9, reviews: 2870, duration: "7 Days", tags: ["Culture", "Food", "Nature"], description: "Zip past Mount Fuji on the Shinkansen, find zen in Kyoto's bamboo groves, feast on fresh sushi at Tsukiji Outer Market, and soak in a steaming onsen under pink sakura petals." },
    { city: "Australia", country: "Australia", image: "/images_v2/dest-australia-v2.jpg", minPrice: "Ks 950,000", rating: 4.6, reviews: 1450, duration: "8 Days", tags: ["Adventure", "Nature", "Beach"], description: "Sail past the iconic Opera House at sunset, snorkel the kaleidoscopic Great Barrier Reef, road-trip the Great Ocean Road, and cuddle koalas in eucalyptus-scented sanctuaries." },
    { city: "Maldives", country: "Maldives", image: "/images_v2/dest-maldives-v2.jpg", minPrice: "Ks 720,000", rating: 4.9, reviews: 1120, duration: "5 Days", tags: ["Beach", "Luxury", "Honeymoon"], description: "Wake to turquoise waves beneath your overwater villa, snorkel with manta rays in coral gardens, dine on a sandbank under the Milky Way, and unwind at a world-class overwater spa." },
    { city: "Italy", country: "Italy", image: "/images_v2/dest-italy-v2.jpg", minPrice: "Ks 890,000", rating: 4.7, reviews: 2100, duration: "7 Days", tags: ["History", "Food", "Art"], description: "Stand in awe at Rome's Colosseum, glide beneath Venice's Bridge of Sighs, sip velvety Chianti in sun-drenched Tuscan vineyards, and twirl forkfuls of handmade carbonara in candlelit trattorias." },
    { city: "India", country: "India", image: "/images_v2/dest-india-v2.jpg", minPrice: "Ks 320,000", rating: 4.4, reviews: 1780, duration: "6 Days", tags: ["Culture", "Spiritual", "Food"], description: "Gaze at the Taj Mahal at sunrise, lose yourself in Jaipur's pink-hued bazaars, find inner peace at a Rishikesh yoga ashram, and taste fragrant biryani in centuries-old spice markets." },
    { city: "Myanmar", country: "Myanmar", image: "/images_v2/dest-myanmar-v2.jpg", minPrice: "Ks 50,000", rating: 4.5, reviews: 980, duration: "6 Days", tags: ["Culture", "Temple", "Nature"], description: "Float over 2,000 ancient pagodas in a Bagan hot air balloon at dawn, witness Shwedagon's golden stupa shimmer at sunset, glide past Inle's one-legged fishermen at sunrise, and uncover a land untouched by time." },
    { city: "Turkey", country: "Turkey", image: "/images_v2/dest-turkey-v2.jpg", minPrice: "Ks 620,000", rating: 4.6, reviews: 1340, duration: "5 Days", tags: ["History", "Culture", "Food"], description: "Gaze at Hagia Sophia's soaring domes, soar above fairy chimneys in a Cappadocia hot air balloon, haggle for silks in the labyrinthine Grand Bazaar, and sip çay where East meets West along the Bosphorus." },
  ],
};

const COLLECTIONS = [
  "tours", "hotels", "cars", "visas", "insurances", "cruises", "mingalar", "blog",
] as const;

export async function GET(request: NextRequest) {
  const { searchParams } = new URL(request.url);
  const reset = searchParams.get("reset") === "true";

  const results: Record<string, number> = {};

  for (const collection of COLLECTIONS) {
    const existing = reset ? [] : await getAll(collection as any);
    if (reset || !existing || existing.length === 0) {
      const items = SEED[collection];
      for (const item of items) {
        await create(collection as any, item);
      }
      results[collection] = items.length;
    } else {
      results[collection] = 0;
    }
  }

  const existingConfig = await getAll("site-config" as any);
  const hasExistingDestinations =
    existingConfig?.[0]?.popularDestinations &&
    existingConfig[0].popularDestinations.length > 0;

  if (!hasExistingDestinations || reset) {
    const base = existingConfig?.[0] || {};
    const store = await import("@/lib/persistentStore");

    for (const item of existingConfig) {
      try { await store.delete_("site-config" as any, item.id || item._id); } catch {}
    }

    const merged = {
      ...base,
      id: "site-config",
      popularDestinations: SEED.popularDestinations,
      updatedAt: new Date().toISOString(),
    };
    await store.create("site-config" as any, merged);
    results["popularDestinations"] = SEED.popularDestinations.length;
  } else {
    results["popularDestinations"] = 0;
  }

  return NextResponse.json({ success: true, seeded: results });
}
